[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python wsgi.py"
healthcheckPath = "/"
healthcheckTimeout = 300

[nixpacks]
python-version = "3.9" 